### ISSUE TITLE
Data Recovery

### ISSUE THREAD

**Issue by mikegillis677** [gmo/arc#9]
Some event occurred between 9/28 at 2:14pm and 9/30 at 10:00am that caused contact data to be lost during the sending of the autoresponder.  It is unknown what caused this to occur, and it is also unknown which contacts were lost (not all contacts on the box were lost).

Justin has requested that we recover the lost data somehow.  The only solution that Carson and Mike can think of is to query Elasticsearch to get the contact data from log message context data.

The most likely query that I can think of at the moment for this is:
`type:ARC AND message: "Received contact to add" AND host: "arc-prod1" AND ctxt_contact.identifiers.channel:"email"`

**Comment by justinmiller24** [comment]
@mikegillis677 Thank you for creating a ticket.

From everything we can tell, the problem is mostly limited to Spanish and Portuguese messages from GodLife. We need to query Kibana and re-import all New Contacts from the following domains between 9/28/2016 @ 14:30 (2:30pm) and 9/30/2016 @ 9:30am

Domains:
- faith.es.godlife.com
- faith.pt.godlife.com

**Comment by mikegillis677** [comment]
Make sure to only replay data that came into host arc-prod1
